# Generated by Django 3.0.14 on 2023-04-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asalto',
            name='imagen',
            field=models.ImageField(default=4, upload_to='upload_to=images/'),
            preserve_default=False,
        ),
    ]
