# Generated by Django 3.0.14 on 2023-04-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_asalto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asalto',
            name='imagen',
            field=models.ImageField(upload_to='asaltos/'),
        ),
    ]
